package com.example.daggerpractice.di;

import com.example.daggerpractice.di.auth.AuthModule;
import com.example.daggerpractice.di.auth.AuthViewModelsModule;
import com.example.daggerpractice.ui.auth.AuthActivity;
import com.example.daggerpractice.ui.main.MainActivity;

import dagger.Module;
import dagger.android.ContributesAndroidInjector;

// MODULES are places for dependencies to live. From here we add them to components
// ONLY Activity declarations should be here

@Module
public abstract class ActivityBuilderModule {

    //    these are submodules generated by dagger
    @ContributesAndroidInjector(
            modules = {
                    AuthViewModelsModule.class,
                    AuthModule.class,
            }
    )

    abstract AuthActivity contributeAuthActivity();
    @ContributesAndroidInjector
    abstract MainActivity contributeMainActivity();

}
